import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
// import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster />
        <header className="">
          <nav className="p-4">
            <ul className="flex gap-4">
              <li className="py-2 px-4 bg-primary text-primary-foreground rounded-lg">
                {/* <Link href="/pets/create">Crear Mascotas</Link> */}
              </li>
              <li className="py-2 px-4 bg-primary text-primary-foreground rounded-lg">
                {/* <Link href="/pets/list">Listado de Mascotas</Link> */}
              </li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
